(()=>{
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const path=p=>!p?'':p;
async function load(name){const r=await fetch(`data/${name}.json?v=${Date.now()}`); if(!r.ok) throw new Error(name); return r.json();}
function bindDetails(root=document){root.querySelectorAll('.detailBtn').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.project-card'); const parent=card.parentElement; parent.querySelectorAll('.project-card.open').forEach(o=>{if(o!==card){o.classList.remove('open');const b=o.querySelector('.detailBtn');if(b)b.textContent=b.dataset.label||'세부보기';}}); card.classList.toggle('open'); btn.textContent=card.classList.contains('open')?'접기':(btn.dataset.label||'세부보기');}));}
async function renderNews(){const root=document.getElementById('newsGrid'); if(!root)return; const d=await load('news'); root.innerHTML=d.items.filter(x=>x.published!==false).map(x=>{const cats=(x.categories?.length?x.categories:[x.category]).filter(Boolean); const imgs=(x.images||[]).map(i=>`<img src="${esc(path(i))}" alt="${esc(x.title)}">`).join(''); return `<article class="card project-card news-card" data-categories="${esc(cats.join('|'))}"><div class="bar">${esc(cats.join(' · '))}</div><span class="status">${esc(x.date||x.status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><button class="btn detailBtn" data-label="기사 자세히 보기">기사 자세히 보기</button><div class="project-detail">${x.location?`<p><b>장소:</b> ${esc(x.location)}</p>`:''}<p>${esc(x.detail)}</p>${imgs?`<div class="news-photos">${imgs}</div>`:''}</div></article>`}).join('')||'<p class="lead">등록된 뉴스가 없습니다.</p>'; bindDetails(root); const buttons=document.querySelectorAll('.filters button[data-filter]'); buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;root.querySelectorAll('.news-card').forEach(c=>{const cs=c.dataset.categories.split('|');c.style.display=(f==='전체'||cs.includes(f))?'block':'none';});}));}
async function renderNotices(){const root=document.getElementById('noticeGrid'); if(!root)return; const d=await load('notices'); const groups=[...new Set(d.items.filter(x=>x.published!==false).map(x=>x.group))]; root.innerHTML=groups.map(g=>`<div class="card"><h3 style="color:var(--gold2)">${esc(g)}</h3>${d.items.filter(x=>x.published!==false&&x.group===g).map(x=>`<details><summary>${esc(x.title)}</summary><p>${esc(x.content)}</p></details>`).join('')}</div>`).join(''); root.querySelectorAll('details').forEach(dt=>dt.addEventListener('toggle',()=>{if(!dt.open)return;dt.closest('.card').querySelectorAll('details[open]').forEach(o=>{if(o!==dt)o.open=false;});}));}
async function renderSchedules(){const root=document.getElementById('scheduleGrid'); if(!root)return; const d=await load('schedules'); root.innerHTML=d.items.filter(x=>x.published!==false).map(x=>`<article class="card project-card"><div class="bar">${esc(x.date)}<br><small>${esc(x.time)}</small></div><span class="tag">${esc(x.organization)}</span><span class="status">${esc(x.status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.place)}</p><button class="btn detailBtn" data-label="세부보기">세부보기</button><div class="project-detail"><p><b>주최·주관:</b> ${esc(x.host)}</p><p><b>행사 내용:</b> ${esc(x.content)}</p></div></article>`).join('')||'<p class="lead">등록된 일정이 없습니다.</p>';bindDetails(root);}
async function renderProjects(){const root=document.getElementById('projectsGrid'); if(!root)return; const d=await load('projects'); root.innerHTML=d.items.filter(x=>x.published!==false).map(x=>`<article class="card project-card"><div class="bar">${esc(x.category)}</div><h3>${esc(x.title)}</h3><span class="tag">${esc(x.place)}</span><span class="status">${esc(x.status)}</span><p>${esc(x.summary)}</p><button class="btn detailBtn" data-label="세부보기">세부보기</button><div class="project-detail"><p>${esc(x.detail)}</p></div></article>`).join('')||'<p class="lead">등록된 실적이 없습니다.</p>';bindDetails(root);}
async function renderGallery(){const root=document.getElementById('galleryGrid'); if(!root)return; const d=await load('gallery'); const items=d.items.filter(x=>x.published!==false); root.innerHTML=items.map(x=>`<div class="photo"><img src="${esc(path(x.image))}" alt="${esc(x.title)}"></div>`).join('')||'<p class="lead">등록된 사진이 없습니다.</p>'; const cap=document.getElementById('galleryCaption'); if(cap)cap.textContent=items.length?`${items[0].date} · ${items[0].description||items[0].title}`:'';}
document.addEventListener('DOMContentLoaded',()=>Promise.allSettled([renderNews(),renderNotices(),renderSchedules(),renderProjects(),renderGallery()]));
})();